### PR TITLE
Added recipe for industrial beehive

### PR DESCRIPTION
**Pull request by myoung008**

### CODE REVIEW

**Comment by bas080** [comment]
Thanks for your commit. However you are using nodes that are part of the homedecor mod. I would preffer a craft using the default nodes. If you preffer using the homedecor nodes I would advice you to check if that mod is installed by the user by using ```minetest.get_modnames()``` and checking if homedecor is in that list. If it isn't you can give it a different craft that uses the nodes of the default game.

If your not sure how to write this you should help you on your way.

```lua
if minetest.get_modpath("homedecor") then
  <your recipe here>
else
  <your default recipe here>
end
```

**Remember to do the soft depend in the depends.txt also**

**depends.txt**
```
default
homedecor?
```

If you make these changes I will add your commit ASAP. Good luck

**Comment by myoung008** [comment]
Homedecor is unnecessary, and I don't have it enabled on my server.  Pipeworks already takes care of homedecor:plastic_sheeting in crafts.lua, lines 88-149 (current git):

    if minetest.get_modpath("homedecor") == nil then
        {register required homedecor items and crafts, including homedecor:plastic_sheeting}

Industrial beehives already require pipeworks, so there is no homedecor dependency.

**Comment by bas080** [comment]
I see now. Then I see no reason to not merge. :+1:

**Comment by myoung008** [comment]
Thanks!

**Pull request merged**
